name: mailman
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  flutter_datetime_picker: ^1.2.8
  dynamic_tabs: ^1.0.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/flutter-icon.png
    - assets/login_logo.png
    - assets/me.jpeg
    - assets/home.jpeg
  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral/Spectral-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spectral/Spectral-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
