name: mailman
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.1
  firebase_core: ^0.4.1+4
  google_sign_in: ^4.0.4
  apple_sign_in: ^0.1.0
  provider: ^4.0.3
  get_it: ^3.0.3
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  flutter_datetime_picker: ^1.2.8
  # dynamic_tabs: ^1.0.2+3
  firebase_storage: ^3.0.6
  image_picker: ^0.6.1+8
  dropdown_formfield: ^0.1.1
  flutter_spinkit: "^4.0.0"
  url_launcher: ^5.2.0
  pull_to_refresh: ^1.5.7
  flutter_email_sender: ^2.2.0
  intl: 0.15.7
  date_range_picker: ^1.0.3
  auto_size_text: ^2.0.2
  flutter_auth_buttons: ^0.5.0
  dio: ^2.1.13
  flare_flutter: ^1.8.1
  uuid: 2.0.1
  # device_info: ^0.4.1+4
  google_fonts: ^0.3.2
  flutter_launcher_icons: ^0.6.1
  shared_preferences: ^0.5.6+1
  firebase_messaging: ^5.0.2
  image: ^2.1.12
dependency_overrides:
  image: ^2.1.12
dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/flutter-icon.png
    - assets/login_logo.png
    - assets/me.jpeg
    - assets/home.png
    - assets/envelop.png
    - assets/glass.png
    - assets/teddy.flr2d
  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral/Spectral-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spectral/Spectral-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
flutter_icons:
  image_path: "assets/icon/icon.png" 
  android: true
  ios: true